### ISSUE TITLE
Review: Recademy

### ISSUE THREAD

**Issue by InRedikaWB** [TEF-Dev/Main#8]
Ревью https://github.com/TEF-Dev/Recademy

**Comment by hrrrrustic** [comment]
==========Mock==========
I. Generators
1. Скорее всего все эти генераторы должны быть статичными
2. А еще это кажется называется фабрика
3. Скорее всего есть смысл немного их смерджить. Первое что пришло в голову, смерджить все генераторы, возвращающий примитивный тип (кажется таких генераторов как минимум их 3)
4. Как следствие из 3, возможно стоит даже по папочкам это разнести!
5. Ну это сильно конечно
https://github.com/TEF-Dev/Recademy/blob/master/Mock/Generators/SkillGenerator.cs#L10
6.  Ради чего такие summary?  Кажется это можно было просто засунуть в название метода
https://github.com/TEF-Dev/Recademy/blob/master/Mock/Generators/SkillGenerator.cs#L22-L24
7. Опять же про summary, почему returns-то везде пустые?
8. Перенос строки, пожалуйста, это ведь даже решарпер сам делать должен, неужели ты спецаильно сделал в одну строку?
https://github.com/TEF-Dev/Recademy/blob/master/Mock/Generators/ProjectInfoesGenerator.cs#L33
9. Честно говоря, я даже не понял, что здесь происходит, но это явно можно сделать на дефолтных методах DateTime намного понятнее и читабельнее 
https://github.com/TEF-Dev/Recademy/blob/master/Mock/Generators/ReviewRequestGenerator.cs#L14-L16
10. Возможно я что-то не понял, но мок.....возвращает налл? Звучит сомнительно
https://github.com/TEF-Dev/Recademy/blob/master/Mock/Generators/ReviewRequestGenerator.cs#L23-L24
11. Ты либо ставишь скобки, либо нет ) + перенос строки, пожалуйста
https://github.com/TEF-Dev/Recademy/blob/master/Mock/Generators/ReviewRequestGenerator.cs#L29-L34
12. .Select ?
https://github.com/TEF-Dev/Recademy/blob/master/Mock/Generators/SkillGenerator.cs#L40-L43
13. Утилитный файлик выглядит грустно и одиноко, уверен, что он действительно нужен?

**Comment by hrrrrustic** [comment]
II Program.cs
1. Ну над хотя бы банально модификаторы проставить
https://github.com/TEF-Dev/Recademy/blob/master/Mock/Program.cs#L12
2. Ну коннекшн стрингу надо спрятать. Самый тупой способ - закинуть в файл и читать с него.
https://github.com/TEF-Dev/Recademy/blob/master/Mock/Program.cs#L14-L15
3. Кажется это явно не паблик
https://github.com/TEF-Dev/Recademy/blob/master/Mock/Program.cs#L17-L18
4. Как раз об этом я и говорил, сделай генераторы статик, чтобы не было такой жижки
https://github.com/TEF-Dev/Recademy/blob/master/Mock/Program.cs#L23-L27
5. Я еще не начал смотреть сам метод, но сразу видно, что ну очень большая и сложная вложенность + ну каммон, это же не алгосы, надо разбить на методы отдельные, а то что-то прям ух.
6. Нейминг. '_' только для приватных
https://github.com/TEF-Dev/Recademy/blob/master/Mock/Program.cs#L34
7. Опять же сразу видно, что очень, ОЧЕНЬ много всяких переменных объявляется, за которыми очень сложно уследить, но оно должно само пофиксится в пункте 5
8. Есть подозрение, что это можно сделать дефолтным методом
https://github.com/TEF-Dev/Recademy/blob/master/Mock/Program.cs#L40-L41
9. Очень много db.SaveChanges(). Зачем? Там явно можно половину выкинуть
10. Добро пожаловать в C# 8.0! Теперь заворачивать юзинг в скобки, что позволяет снизить вложенность и увеличить читаемость 
https://github.com/TEF-Dev/Recademy/blob/master/Mock/Program.cs#L50
11. Я думаю со сборщиком мусора плакало полCLR. Не насилуй его, объявляй переменные как можно вложенней, если они тебе нужны "на разочек"
12. Это можно закинуть в генератор как статик метод, возвращающий контекст
https://github.com/TEF-Dev/Recademy/blob/master/Mock/Program.cs#L128-L134
13. Я не стал вникать, что там вообще происходит, это очень сложно, не очевидно и времязатратно - пункт 5

**Comment by hrrrrustic** [comment]
==========Recademy==========
I Dto
1. У большинства дтошек сильно скачет количество ссылок на их свойства, наводит на мысль, что это не оч дтошки
2. Очень много паблик сетов. Кажется есть три подхода. 
Первый для Шершней - оставляете паблик сеты, но убираете конструкторы и инициализируете дто через { }. 
Второй для кисиков - методы по типу .Create + приватный конструктор(обязательно надо оставить пустой паблик конструктор!). Довольно удобно, когда дто билдится из другого объекта, над параметрами проводится какое-то шамамнство или вообще в конструктор отправляется параметр, про который знать-то и не надо при создании.
Третий для обычный работяг - просто обычный паблик конструктор, принимающий параметры. Ну тут даже добавить нечего
3. Там какая-то дичь с листом объектов и одиночным объектом
4. Имхо, пустой паблик конструктор лучше прописывать явно
5. Это был дикий костыль, чтобы оно нормально отображалось при выборе проекта для добавления, но надо бы сделать это нормально
https://github.com/TEF-Dev/Recademy/blob/master/Recademy/Dto/GhRepositoryDto.cs#L10-L13
6. Методы Of. Во-первых, название... ну какое-то фи, а во-вторых, снести все.
7. Решарпер ругается на название - а с решарпером я бы не стал спорить
https://github.com/TEF-Dev/Recademy/blob/master/Recademy/Dto/UserInfoDto.cs#L10

**Comment by hrrrrustic** [comment]
II Models
1. Ну, я так понял это все-таки DbModels, можно переименовать папочку!
2. По самим моделям сказать нечего, просто таблчики в бд, но вся вот эта тема с инклюдами - либо снести, либо придумать что-то, чтобы я потом ручками не писал в каждый сервис инклюд

**Comment by hrrrrustic** [comment]
III Pages
1. Ну, фейк авторизацию надо убирать ))
2. Error либо сносить, либо писать свой
3. Ну index страница Hello World это тоже не серьезно )) Снести или написать свою
4.  Ну в верстку не лезу, только про вот это надо не забыть
https://github.com/TEF-Dev/Recademy/blob/master/Recademy/Pages/ProfilePage.razor#L121-L122
5. А нужно ли это?
https://github.com/TEF-Dev/Recademy/blob/master/Recademy/Pages/RatingPage.razor#L25
6. Доступ
https://github.com/TEF-Dev/Recademy/blob/master/Recademy/Pages/ReviewPage.razor#L53-L55

**Comment by hrrrrustic** [comment]
IV Shared
1. C MainLayout'ом надо что-то сделать, он вроде и не нужен, а вроде..?
2. Автосгенеренная менюшка это круто, но может хоть цвет поменять? ))

**Comment by hrrrrustic** [comment]
V Utils
1. Ну, целую папочку под это наверно зря, хватило бы просто статик Tools
2. Ну опять же, как и с коннекшн стрингой, все что сенсетив - спрятать

**Comment by hrrrrustic** [comment]
VI Types
1. Там конечно нумерация по умолчанию с 0(?) идет, но, имхо, лучше явно указать

**Comment by hrrrrustic** [comment]
VII Services
0. Контекст явно не паблик и уж точно без возможности изменения
1. А можно скобочки ровно? И перенос строки еще!
https://github.com/TEF-Dev/Recademy/blob/master/Recademy/Services/AchievementService.cs#L19-L33
2. Возможно стоит посмотреть в сторону switch (C# 8.0)
https://github.com/TEF-Dev/Recademy/blob/master/Recademy/Services/AchievementService.cs#L14-L33
3. Ну это сильно
https://github.com/TEF-Dev/Recademy/blob/master/Recademy/Services/AuthService.cs
4. Ну это сильно
https://github.com/TEF-Dev/Recademy/blob/master/Recademy/Services/GameficationService.cs
5. Подумать еще несколько раз про инклюды
https://github.com/TEF-Dev/Recademy/blob/master/Recademy/Services/ProjectService.cs#L23
6. Пункт 5 + зачем там создавать переменную, почему не сразу return ?
https://github.com/TEF-Dev/Recademy/blob/master/Recademy/Services/TagService.cs#L20-L33
7. ah shit here we go again
https://github.com/TEF-Dev/Recademy/blob/master/Recademy/Services/ReviewService.cs#L26-L28
8. Это даже не используется
https://github.com/TEF-Dev/Recademy/blob/master/Recademy/Services/GithubService.cs#L20-L21
9. Такое можно вынести в приватные методы типа BuildSomething
https://github.com/TEF-Dev/Recademy/blob/master/Recademy/Services/GithubService.cs#L23-L24
10. Выглядит как говно, но это апи гитхаба + октокит сам это не делает, наверно следует вынести в приватный метод
https://github.com/TEF-Dev/Recademy/blob/master/Recademy/Services/GithubService.cs#L27-L47
11. Перенос строки классная штука, можно отделять какие-то логические куски
https://github.com/TEF-Dev/Recademy/blob/master/Recademy/Services/GithubService.cs#L52-L62
12. Опять же вынести в приват + юзлесс переменные
https://github.com/TEF-Dev/Recademy/blob/master/Recademy/Services/GithubService.cs#L65-L87
13. Есть подозрение, что это можно сделать линком 
https://github.com/TEF-Dev/Recademy/blob/master/Recademy/Services/ReviewService.cs#L37-L42
14. Дратути, а вот и прогрузка страницы по 5+ секунд. ОЧЕНЬ МНОГО ToList(), зачем? Ну сделайте IEnumerable аргумент в IsValid() и все.
15. Пункт 14
https://github.com/TEF-Dev/Recademy/blob/master/Recademy/Services/ReviewService.cs#L57-L59

**Comment by InRedikaWB** [comment]
update:
1. Все еще актуально, это нужно вырезать:
https://github.com/TEF-Dev/Recademy/blob/master/Recademy/Dto/GhRepositoryDto.cs#L10-L13

2. Нормально написать всякие инклюды.
